"""empty message

Revision ID: 5565efccc453
Revises: 302cfc13c2ae
Create Date: 2022-07-09 15:00:44.350033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5565efccc453'
down_revision = '302cfc13c2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('serverlists_userId_fkey', 'serverlists', type_='foreignkey')
    op.drop_constraint('serverlists_serverId_fkey', 'serverlists', type_='foreignkey')
    op.create_foreign_key(None, 'serverlists', 'servers', ['serverId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'serverlists', 'users', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serverlists', type_='foreignkey')
    op.drop_constraint(None, 'serverlists', type_='foreignkey')
    op.create_foreign_key('serverlists_serverId_fkey', 'serverlists', 'servers', ['serverId'], ['id'])
    op.create_foreign_key('serverlists_userId_fkey', 'serverlists', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
