"""empty message

Revision ID: 5f9a56156560
Revises: 2d80677c8af5
Create Date: 2022-07-07 12:39:03.140194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9a56156560'
down_revision = '2d80677c8af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendlist',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('friendId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friendId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userId', 'friendId')
    )
    op.add_column('messages', sa.Column('createdate', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthday')
    op.drop_column('messages', 'createdate')
    op.drop_table('friendlist')
    # ### end Alembic commands ###
